env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  'no-console': 'off',
  'no-unused-vars': 'warn',
  'react/destructuring-assignment': 'warn',
  'spaced-comment': 'warn',
  'react/jsx-no-bind': 'warn',
  'no-alert': 'off',
}
